### PR TITLE
Fix liota package manager bug on incomplete command input

### PR DESCRIPTION
**Pull request by winniex1**

### CODE REVIEW

**Comment by winniex1** [comment]
A bug was reported as "Liota : Liota package manager thread crashes on incomplete command to package manager". Please refer "https://jira-euc.eng.vmware.com/jira/browse/IOT-2706" for detailed explanation.
In a word, if you execute an Incomplete Command: sudo liotad/liotapkg.sh load, later no other commands could be executed. 
In the input, since only "load" command without any arguments (i.e, msg length is only 1), no msg[1] could be accessed, which caused a crash.
That's why I fix the issue. I don't want to change the code framework since it has been well tested. Just we have this bug of accessing char beyond range.

**Comment by gkmccready** [comment]
Your fix is fine. But we should address the rest at some point, including the questions I asked.

**Comment by winniex1** [comment]
Yes, will create an issue to memorize the rest.

**Comment by winniex1** [comment]
Merge since Glen agreed the fix is fine for the bug.

**Pull request merged**
